### ISSUE TITLE
C++ in Metacell CLI

### ISSUE THREAD

**Issue by Ayush7614** [metacall/gsoc-2022#4]
I think C++ is a good fit for "MetaCall CLI Bootstrapping / Refactor" project

and i would also like to contribute to this project in C++ in GSOC22

**Comment by Ayush7614** [comment]
@viferga ?

**Comment by viferga** [comment]
@Ayush7614 sorry for late answer, would you like to discuss it in our chats?

https://github.com/metacall/gsoc-2022#find-us
